//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiRD_Splot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class polish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal polish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PiRD_Splot.polish", typeof(polish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorytm wyznaczania splotu.
        /// </summary>
        internal static string algorytm_wyznaczania_splotu {
            get {
                return ResourceManager.GetString("algorytm_wyznaczania_splotu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DALEJ.
        /// </summary>
        internal static string dalej {
            get {
                return ResourceManager.GetString("dalej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definicja splotu.
        /// </summary>
        internal static string definicja_splotu {
            get {
                return ResourceManager.GetString("definicja_splotu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Dokonanie zamiany zmiennych.
        /// </summary>
        internal static string dokonanie_zamiany_zmiennych {
            get {
                return ResourceManager.GetString("dokonanie_zamiany_zmiennych", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilustracja.
        /// </summary>
        internal static string ilustracja {
            get {
                return ResourceManager.GetString("ilustracja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilustracja (1).
        /// </summary>
        internal static string ilustracja_1 {
            get {
                return ResourceManager.GetString("ilustracja_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilustracja (2).
        /// </summary>
        internal static string ilustracja_2 {
            get {
                return ResourceManager.GetString("ilustracja_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilustracja (3).
        /// </summary>
        internal static string ilustracja_3 {
            get {
                return ResourceManager.GetString("ilustracja_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja.
        /// </summary>
        internal static string informacja {
            get {
                return ResourceManager.GetString("informacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Obliczanie wartości splotu dla koljnych t.
        /// </summary>
        internal static string obliczanie_wartosci_splotu {
            get {
                return ResourceManager.GetString("obliczanie_wartosci_splotu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jak funkcja f2(t).
        /// </summary>
        internal static string odp_3_1 {
            get {
                return ResourceManager.GetString("odp_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jak odwrócona funkcja f2(t), czyli f2(-t).
        /// </summary>
        internal static string odp_3_2 {
            get {
                return ResourceManager.GetString("odp_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jak przesunięta funkcja f2(t), czyli f2(t-a).
        /// </summary>
        internal static string odp_3_3 {
            get {
                return ResourceManager.GetString("odp_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jak funkcja f1(t).
        /// </summary>
        internal static string odp_3_4 {
            get {
                return ResourceManager.GetString("odp_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o kształcie podobnym jak w poprzednim przypadku.
        /// </summary>
        internal static string odp_3_5 {
            get {
                return ResourceManager.GetString("odp_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inny niż wymienione wyżej.
        /// </summary>
        internal static string odp_3_6 {
            get {
                return ResourceManager.GetString("odp_3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź.
        /// </summary>
        internal static string odpowiedz {
            get {
                return ResourceManager.GetString("odpowiedz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpowiedź.
        /// </summary>
        internal static string podpowiedz {
            get {
                return ResourceManager.GetString("podpowiedz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POWRÓT.
        /// </summary>
        internal static string powrot {
            get {
                return ResourceManager.GetString("powrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Przygotowanie do zamiany zmiennych.
        /// </summary>
        internal static string przygotowanie_do_zamiany_zmiennych {
            get {
                return ResourceManager.GetString("przygotowanie_do_zamiany_zmiennych", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPLOT FUNKCJI.
        /// </summary>
        internal static string splot_funkcji {
            get {
                return ResourceManager.GetString("splot_funkcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPRAWDŹ.
        /// </summary>
        internal static string sprawdz {
            get {
                return ResourceManager.GetString("sprawdz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedmiotem ćwiczenia jest wyznaczenie funkcji splotu.
        ///Program składa się z 9 kroków oraz kilku problemów, które należy rozwiązać..
        /// </summary>
        internal static string tekst_1_1 {
            get {
                return ResourceManager.GetString("tekst_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niniejsza strona prezentuje graficzny sposób wyznaczania splotu dwóch funkcji f1(t) i f2(t) pokazanych na rysunku. Po przeanalizowaniu wzoru definiującego splot wykonaj kroki algorytmu przedstawione poniżej..
        /// </summary>
        internal static string tekst_2_1 {
            get {
                return ResourceManager.GetString("tekst_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaki kształt ma funkcja splotu, jeżeli funkcje f1(t) i f2(t) mają postaci pokazane na rysunkach obok?.
        /// </summary>
        internal static string tekst_3_1 {
            get {
                return ResourceManager.GetString("tekst_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teoria.
        /// </summary>
        internal static string teoria_1 {
            get {
                return ResourceManager.GetString("teoria_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przetwarzanie i Rozpoznawanie Dźwięku - Splot Funkcji.
        /// </summary>
        internal static string tytul_okna {
            get {
                return ResourceManager.GetString("tytul_okna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wnioski.
        /// </summary>
        internal static string wnioski_1 {
            get {
                return ResourceManager.GetString("wnioski_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadzenie.
        /// </summary>
        internal static string wprowadzenie {
            get {
                return ResourceManager.GetString("wprowadzenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadania (1).
        /// </summary>
        internal static string zadania_1 {
            get {
                return ResourceManager.GetString("zadania_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadania (2).
        /// </summary>
        internal static string zadania_2 {
            get {
                return ResourceManager.GetString("zadania_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadania (3).
        /// </summary>
        internal static string zadania_3 {
            get {
                return ResourceManager.GetString("zadania_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadanie 1.
        /// </summary>
        internal static string zadanie1 {
            get {
                return ResourceManager.GetString("zadanie1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Zakończenie algorytmu.
        /// </summary>
        internal static string zakonczenie_algorytmu {
            get {
                return ResourceManager.GetString("zakonczenie_algorytmu", resourceCulture);
            }
        }
    }
}
